#!/bin/bash

# check who owns the working directory
USER_ID=$(stat -c "%u" $PWD)
USER_GROUP_ID=$(stat -c "%g" $PWD)

if [ "$USER_ID" -eq "0" ]; then
    echo "Detected User Id 0 - are you on Windows? Setting USER_ID=1000"
    USER_ID=1000
fi

if [ "$USER_GROUP_ID" -eq "0" ]; then
    echo "Detected Group id 0 - are you on Windows? Setting USER_GROUP_ID=1000"
    USER_GROUP_ID=1000
fi

# set the node run uid to the user id we just retrieved
NODE_RUN_UID=${NODE_RUN_UID:=${USER_ID}}
NODE_RUN_USER=${NODE_RUN_USER:=user}
NODE_RUN_GID=${NODE_RUN_GID:=${USER_GROUP_ID}}
NODE_RUN_GROUP=${NODE_RUN_GROUP:=user}

# test to see if the user already exists
NODE_RUN_USER_TEST=$(grep "[a-zA-Z0-9\-\_]*:[a-zA-Z]:${NODE_RUN_UID}:" /etc/passwd)
NODE_RUN_GROUP_TEST=$(getent group ${NODE_RUN_GROUP})

# Make sure the group NODE_RUN_GROUP with NODE_RUN_GID exists
if [ -n "${NODE_RUN_GROUP_TEST}" ]; then
    # group already exists - we do not need to do anything
    echo "group already exists (result was ${NODE_RUN_GROUP_TEST})."
else
    echo "group does not exist - trying to create it ..."
    # in case the group if the group id (NODE_RUN_GID) already exists, the next command will fail, 
    # but we will continue to use the NODE_RUN_GID
    groupadd -g ${NODE_RUN_GID} ${NODE_RUN_GROUP}
fi



# Update the user to the configured UID and group
if [ -n "${NODE_RUN_USER_TEST}" ]; then
    echo "Update user '$NODE_RUN_USER'"

    usermod -l ${NODE_RUN_USER} $(id -un ${NODE_RUN_UID})
    usermod -u $NODE_RUN_UID -g $NODE_RUN_GROUP $NODE_RUN_USER

# Else create the user with the configured UID and group
else
    echo "Create user '$NODE_RUN_USER'"

    # Create the user with the corresponding group
    groupadd $NODE_RUN_GROUP
    useradd -u $NODE_RUN_UID -g $NODE_RUN_GROUP -d /home/$NODE_RUN_USER $NODE_RUN_USER
fi

# export home directory (required by npm/node to store some settings)
export HOME=/home/$NODE_RUN_USER

# check if home directory exists
if [ ! -d "$HOME" ]; then
    mkdir "$HOME"
fi

# make sure home directory has the correct permissions
chown -R ${NODE_RUN_USER}:${NODE_RUN_GID} "$HOME"

# specify that we want to use bash as our standard shell
export SHELL=/bin/bash

echo "Running command '$*'"
# start a script
exec su -p - ${NODE_RUN_USER} -c "$*"
