version: 2
updates:
- package-ecosystem: npm
  directory: "/{{ cookiecutter.project_slug }}"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/Vienna
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 15.0.0
  - dependency-name: "@angular/animations"
    versions:
    - 11.2.10
    - 11.2.11
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/router"
    versions:
    - 11.2.10
    - 11.2.11
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/common"
    versions:
    - 11.2.10
    - 11.2.11
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/forms"
    versions:
    - 11.2.10
    - 11.2.11
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/core"
    versions:
    - 11.2.10
    - 11.2.11
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
    - 5.2.2
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1102.6
    - 0.1102.7
    - 0.1102.8
    - 0.1102.9
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.2
    - 11.1.3
    - 11.1.4
    - 11.2.0
    - 11.2.1
    - 11.2.10
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/platform-browser"
    versions:
    - 11.2.10
    - 11.2.11
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/platform-browser-dynamic"
    versions:
    - 11.2.10
    - 11.2.11
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@swimlane/ngx-datatable"
    versions:
    - 19.0.0
  - dependency-name: tslib
    versions:
    - 2.1.0
  - dependency-name: "@ng-bootstrap/ng-bootstrap"
    versions:
    - 9.1.0
  - dependency-name: "@ngx-translate/http-loader"
    versions:
    - 6.0.0
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: "@uirouter/angular"
    versions:
    - 8.0.1
  - dependency-name: "@fortawesome/angular-fontawesome"
    versions:
    - 0.8.2
  - dependency-name: ngx-anx-forms
    versions:
    - 0.3.1
  - dependency-name: "@ngx-translate/core"
    versions:
    - 13.0.0
  - dependency-name: "@ng-select/ng-select"
    versions:
    - 6.1.0
  - dependency-name: ngx-toastr
    versions:
    - 13.2.1
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: jasmine-core
    versions:
    - 3.7.0
    - 3.7.1
  - dependency-name: rxjs
    versions:
    - 6.6.6
  - dependency-name: puppeteer
    versions:
    - 5.5.0
    - 6.0.0
    - 7.0.0
    - 7.0.1
    - 7.0.4
    - 8.0.0
  - dependency-name: zone.js
    versions:
    - 0.11.4
  - dependency-name: rxjs-compat
    versions:
    - 6.6.6
  - dependency-name: jasmine-spec-reporter
    versions:
    - 6.0.0
  - dependency-name: ts-node
    versions:
    - 9.1.1
  - dependency-name: ngx-resource-factory
    versions:
    - 1.1.0
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.3
  - dependency-name: "@storybook/angular"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.17
  - dependency-name: "@angular/language-service"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.2.0
  - dependency-name: "@storybook/addon-actions"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.17
  - dependency-name: "@storybook/addon-knobs"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.17
